### ISSUE TITLE
unhandled null values in constructor steps

### ISSUE THREAD

**Issue by crowlKats** [WICG/urlpattern#117]
https://wicg.github.io/urlpattern/#dom-urlpattern-urlpattern

> Let processedInit be the result of process a URLPatternInit given init, "pattern", null, null, null, null, null, null, null, and null\.

Directly after this it compiles components for various values of `processedInit`, but nowhere does it dictate how to handle null of the processedInit values, and `compile a component` takes a string, nothing optional

**Comment by wanderview** [comment]
Good catch.  The "compile a component" algorithm should convert `null` to `"*"`.
