### ISSUE TITLE
`process pathname for init` is missing an empty string check

### ISSUE THREAD

**Issue by lucacasonato** [WICG/urlpattern#122]
Given this case:

```json
{
    "pattern": [{ "pathname": "/foo/bar" }],
    "inputs": [{ "pathname": "/foo/bar" }],
    "expected_match": {
       "pathname": { "input": "/foo/bar", "groups": {} }
    }
}
```

When `process pathname for init` is called from `process a URLPatternInit`, the "protocol" passed to `process pathname for init` is the empty string (`""`). The spec says to use the "can-not-be-a-base" path parsing for this, as the scheme is not special. Really this should be using the "standard" parsing (see [Chromium implementation](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/url_pattern/url_pattern_canon.cc;l=361-362;drc=140dd96afd8d4e58d70e89e3cc4a128ec3dd1a54)). The spec should say:

> If protocolValue is an empty string, or if protocolValue is a special scheme, then return the result of running canonicalize a pathname given pathnameValue.

**Comment by wanderview** [comment]
Hmm, I'm not sure I realized I was allowing the empty string there.  I see, though, that its needed for canonicalization to work right for `p.test({ pathname: '/foo' })` type match input.

Good catch.  I'll update the spec.  It probably deserves a note as well.
