### ISSUE TITLE
Steps outlined in `canonicalize a pathname` do not align with tests

### ISSUE THREAD

**Issue by lucacasonato** [WICG/urlpattern#128]
The `canonicalize a pathname` steps in the spec take a string, run it through the path parser, and return the normalized path. Essentially it is doing the following:

```js
function canonicalizePathname(path) {
  const url = new URL("http://dummy.test");
  url.pathname = path;
  return url.pathname;
}
```

The path returned from `url.pathname` is always absolute: if a path of `foo/bar` is given to the setter, the getter will return `/foo/bar`. A `/` will be prepended.

The test cases do not agree with this though (see ones shown below). They expect relative paths to be returned as relative paths from the `canonicalizePathname` function. The Chromium implementation [does this via a proprietary `CanonicalizePartialPath` function][chromium], not described or exposed in the URL specification.

<details>
<summary>The test cases which expect this behaviour.</summary>

```json
[
  {
    "pattern": [{ "pathname": "/foo/bar" }],
    "inputs": [{ "pathname": "foo/bar" }],
    "expected_match": null
  },

  {
    "pattern": [{ "pathname": "foo/bar" }],
    "inputs": [ "https://example.com/foo/bar" ],
    "expected_match": null
  },

  {
    "pattern": [{ "pathname": ":name.html", "baseURL": "https://example.com" }],
    "inputs": [ "https://example.com/foo.html"] ,
    "exactly_empty_components": [ "username", "password", "port", "search",
                                  "hash" ],
    "expected_obj": {
      "pathname": "/:name.html"
    },
    "expected_match": {
      "protocol": { "input": "https", "groups": {}},
      "hostname": { "input": "example.com", "groups": {}},
      "pathname": { "input": "/foo.html", "groups": { "name": "foo" }}
    }
  },

  {
    "pattern": [{ "pathname": "var x = 1;" }],
    "inputs": [{ "protocol": "javascript", "pathname": "var x = 1;" }],
    "expected_obj": {
      "pathname": "var%20x%20=%201;"
    },
    "expected_match": null
  },

  {
    "pattern": [{ "protocol": "(https|javascript)", "pathname": "var x = 1;" }],
    "inputs": [{ "protocol": "javascript", "pathname": "var x = 1;" }],
    "expected_obj": {
      "pathname": "var%20x%20=%201;"
    },
    "expected_match": null
  },

  {
    "pattern": [{ "pathname": "var x = 1;" }],
    "inputs": [{ "pathname": "var x = 1;" }],
    "expected_obj": {
      "pathname": "var%20x%20=%201;"
    },
    "expected_match": {
      "pathname": { "input": "var%20x%20=%201;", "groups": {}}
    }
  },
]
```
</details>

[chromium]: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/url_pattern/url_pattern_canon.cc;l=371-376;drc=e6d4943e8896e09a0b28810b349c049f3ec28ede.

**Comment by wanderview** [comment]
Probably the most expedient thing to do here would be to do what the polyfill does for this case:

https://github.com/wanderview/urlpattern-polyfill/blob/1be3dda1061737490f8dbb8d76fdf970e3f1a022/src/url-utils.ts#L263

Basically strip the leading slash if the original input does not have a leading slash.  I'll write a PR for this later today or tomorrow.

**Comment by wanderview** [comment]
We also need to only strip the leading slash for the pattern encoding callback, but not for "process pathname for init".

**Comment by wanderview** [comment]
Actually, I take that back.  We also use the same logic for "process pathname for init".  The comment here provides some of the reasoning:

https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/url_pattern/url_pattern_canon.cc;l=396;drc=d78439a4b3e959d8f0fca925eaba89758164ccc9
