### ISSUE TITLE
Editorial: "Else" is not Infra language

### ISSUE THREAD

**Issue by annevk** [WICG/urlpattern#144]
Please use "otherwise".

**Comment by miketaylr** [comment]
Maybe https://github.com/whatwg/infra/issues/180 should be fixed - it's not clear to me how reading https://infra.spec.whatwg.org/ prescribes using "otherwise" (other than by pattern matching from usage like https://infra.spec.whatwg.org/#set-append or https://infra.spec.whatwg.org/#stack-pop).

**Comment by annevk** [comment]
Yeah it should be.
