### ISSUE TITLE
pattern string canonicalization with wildcards can result in different meanings

### ISSUE THREAD

**Issue by wanderview** [WICG/urlpattern#145]
Currently, when generating canonical pattern strings the algorithm always translates `.*` regex values into wildcards like `*`.  Unfortunately, this can result in a change of meaning if it does not consider the values before the regexp group.

Consider, this:

  `(foo)(.*)`

Gets "canonicalized" to:

  `(foo)*`

If this is parsed again the `*` is treated as a modifier of `(foo)` instead of as a wildcard.

The algorithm should be fixed to look at the preceding part to determine if its safe to convert a `.*` regexp into a wildcard character.

**Comment by wanderview** [comment]
Another type of problem here with:

`{:foo}(.*)`

Assuming we fix this not to convert `(.*)` to `*`, we also need to avoid accidentally changing it to:

`:foo(.*)`

That changes the pattern from two groups to a single group with a custom name and wildcard regexp.

**Comment by wanderview** [comment]
Another slight variation on the problem:

`{:foo}bar`

Becomes:

`:foobar`

**Comment by lucacasonato** [comment]
@wanderview The WPTs seem to have landed for this, and the Chromium change also seems to have landed, but there is no spec change yet. Is this in the works?

**Comment by lucacasonato** [comment]
Ah no, it is #152. Sorry.

**Comment by wanderview** [comment]
Sorry, I went on holiday prior to finishing the spec changes.  It will be the first thing I do now that I'm back.

**Comment by wanderview** [comment]
I believe this is fixed in the spec now.  I will work on updating the polyfill.

**Comment by wanderview** [comment]
We found another issue along these lines:

`/foo\\/:bar?`

Should require the second slash because the escape prevents it from becoming a prefix to the `:bar?` group.  Pattern string generation, however, produces this:

`/foo/:bar?`

This was found by our fuzzer here:

https://bugs.chromium.org/p/chromium/issues/detail?id=1285620

**Comment by wanderview** [comment]
Another one of these was found by the fuzzer:

https://bugs.chromium.org/p/chromium/issues/detail?id=1289115

In this case if an implicit prefix is before `:foo` group it can incorrectly prevent us from protecting from trailing fixed characters.
