### ISSUE TITLE
"The result of running is a valid name code poin..."

### ISSUE THREAD

**Issue by negentropicdev** [WICG/urlpattern#171]
https://wicg.github.io/urlpattern/#ref-for-options①⓪

> The result of running is a valid name code point given part’s suffix's first code point and the boolean false is true

Assuming it should be "boolean value is true"

**Comment by wanderview** [comment]
Sorry, the text is confusing but I think correct.  The "boolean false" part is the second argument to "is a valid name code point" and the "is true" part is checking the return value of "is a valid name code point".
