### ISSUE TITLE
Steps `create a component match result` never increments index

### ISSUE THREAD

**Issue by tjosepo** [WICG/urlpattern#173]
Tiny issue I noticed in the loop of https://wicg.github.io/urlpattern/#create-a-component-match-result, while working on an implementation:

> 4. Let _index_ be 1.
> 5. While _index_ is less than Get(execResult, "length"):
> > 1. Let name be component’s group name list[_index_ − 1].
> > 2. Let value be Get(execResult, ToString(_index_).
> > 3. Set groups[name] to value.

_index_ is never incremented, and the loop will never end.

**Comment by wanderview** [comment]
Thanks for catching this!
