### ISSUE TITLE
Consider creating a RFC for base functionality

### ISSUE THREAD

**Issue by pmeenan** [WICG/urlpattern#180]
It might be worthwhile to create an internet draft/RFC for the core functionality of URL matching and constructing an URLPattern from an input string. That would make it possible (or at least easier) to use for parts of the stack outside of WICG.

As a concrete example, we're working on [Compression Dictionary content encoding](https://github.com/WICG/compression-dictionary-transport) which is negotiated at the HTTP layer and uses a [URL match pattern](https://www.ietf.org/archive/id/draft-meenan-httpbis-compression-dictionary-04.html#name-match) for the compression dictionaries. Parts of it will end up in the fetch and HTML specs but the core functionality is going to be in a RFC.  Currently it's a simple wildcard expansion but the use case is not significantly different from the service worker routing use cases (and the web extension URL filter use case).

**Comment by domenic** [comment]
Why would this make it easier? IETF specs are able to refer to web specs, and do so frequently.

**Comment by pmeenan** [comment]
Thanks, good to know.  I haven't seen any of the HTTP RFCs refer to whatwg specs (usually see it the other way around) but it could just be my limited exposure to date.
