### ISSUE TITLE
Hash test matching different from path matching

### ISSUE THREAD

**Issue by jvailius** [WICG/urlpattern#192]
Hi, does someone know if there a particular reason for this behavior: The path is (correctly I guess) not matched but the hash is.

```js
const pattern = new URLPattern("/#/books/:id", "http://example.com");
pattern.test("http://example.com/#/books/1/page/0") // true
```

```js
const pattern = new URLPattern("/books/:id", "http://example.com");
pattern.test("http://example.com/books/1/page/0") // false
```
Thank you.

Tested with Google Chrome 117.0.5938.149 (Official Build) (64-bit)

**Comment by jeremyroman** [comment]
`/` has special treatment as a separating character in the pathname component, but not in the hash (where / has special meaning only for libraries that choose to treat it that way).

As one workaround, you can use a regex group, like so:

```javascript
const pattern = new URLPattern('/#/books/:id([^/]+)', 'http://example.com');
pattern.test("http://example.com/#/books/1/page/0") // false
```
