### ISSUE TITLE
pass patterns as strings to service worker API

### ISSUE THREAD

**Issue by wanderview** [WICG/urlpattern#21]
Per discussions leading up to https://github.com/w3c/ServiceWorker/issues/1468#issuecomment-707930060 there is a growing consensus that patterns should be passed to the service worker API as strings and not objects.

While that integration will ultimately be spec'd in the service worker repo I'm filing an issue here to track it and for eventually updating the explainer.

**Comment by sisidovski** [comment]
[ServiceWorker Static Routing API](https://github.com/WICG/service-worker-static-routing-api) provides a way to bypass service worker in some specific URLs in the registered scope.

If the scope pattern matching for the service worker registration is required for the bypassing purpose, it can achievable by the the static routing API. [The example](https://github.com/WICG/service-worker-static-routing-api/tree/main#bypassing-serviceworker-for-particular-resources) in the explainer describes how to bypass SW on pages in the scope.

I'll close this issue but feel free to reopen if needed.
