### ISSUE TITLE
consider how to handle changes to ecma-262 regex standard

### ISSUE THREAD

**Issue by wanderview** [WICG/urlpattern#25]
While reviewing some of my prototype code @jeremyroman raised the point that we need to consider what to do when ecma-262 regex changes upstream in the spec and js implementations.

The path-to-regexp syntax we are using embeds regular expressions and while it largely can pass the expressions through it does need to have some knowledge of internal regex structure.  This is mainly associated with detecting nested groupings and forbidding unnamed capture groups.

Its possible our initial parse algorithm that works for these scenarios today could break if regex syntax is expanded in the future.  We might start accidentally blocking the use of a new feature that is added, etc.  We should consider what do in this situation.

I'm filing this issue so we don't forget, but I'm not sure there is anything we can do immediately.  I don't think we want to embed a complete regex parser in urlpattern directly.  Instead I think we would want to consider the impact to regex changes on a case-by-case basis and asses how to adapt urlpattern, if necessary.  My expectation is that regex does not change too frequently, so this should not be excessively burdensome.

**Comment by annevk** [comment]
cc @mathiasbynens

**Comment by mathiasbynens** [comment]
Have you considered implicitly enabling the `u` flag for all regexps? This matches the HTML `pattern` attribute, and guarantees that unknown escapes (e.g. `\m`) throw an exception instead of silently being treated as an escaped character (e.g. `m`). This is what future-proofs regular expressions: we can add new escape sequences to the `u` flag without significant back-compat concerns, because we go from throwing an exception to doing something useful.

**Comment by wanderview** [comment]
One issue I ran into while trying to add the `u` flag to the regexp compilation is any pattern blowing up that includes the `=` character.  It seems path-to-regexp escapes `=`:

https://github.com/pillarjs/path-to-regexp/blob/b39edd433c173257062883f58867feecee660fd4/src/index.ts#L424

If I remove `=` from the escape list then it works fine.  Is it safe to use `=` in regexp without escaping it?  It seems to only be used in assertions that start with `?`, etc.

**Comment by wanderview** [comment]
@blakeembrey, would you be ok with path-to-regexp dropping the `=` escape?

**Comment by blakeembrey** [comment]
Sounds good to me. I think I pulled the original escapes from https://github.com/component/escape-regexp/blob/5ce923c1510c9802b3da972c90b6861dd2829b6b/index.js#L11 a while back, I can make any changes needed here.

**Comment by wanderview** [comment]
Hmm, it also has trouble with these escape characters:  `!` and `:`.  I think it might have trouble with `{` and `}`, but we end up percent encoding those.
