### ISSUE TITLE
should we make empty string port values and the default port number equivalent?

### ISSUE THREAD

**Issue by wanderview** [WICG/urlpattern#31]
Consider a situation where you only want to support the default port a protocol; e.g. 443 for https.  To do this today you would need to specify a port pattern like `port: '(443)?'`.

As an alternative we could make the empty string port and the default port number equivalent.  Then you could write a pattern like `port: ''` which would match either the default port explicitly set or the empty string for the port.  It would not match other port values.

My inclination is to maybe not do this at first and only add it later if requested.  I'm not sure how backward compatible that approach is, though.

**Comment by domenic** [comment]
How I kind of anticipated this working was that if you don't provide a `port` dictionary member, then the port needs to match the default port for the protocol. But hmm, that makes some other use cases tricky.

**Comment by wanderview** [comment]
My initial problem state here is wrong.  URL canonicalization will automatically coerce default port numbers to the empty string.  Since test() and exec() inputs are canonicalized the pattern would need to target just the empty string.

We could also try to canonicalize pattern ports based on default port numbers, but I will defer that to #33.
