### ISSUE TITLE
consider allowing an 'origin: foo' init attribute

### ISSUE THREAD

**Issue by wanderview** [WICG/urlpattern#32]
When passing an init dictionary to the URLPattern constructor you can set things like port, hostname, and port either through setting values for these components individually:

```javascript
new URLPattern({ protocol: 'https', hostname: 'example.com', port: '' });
```

Or through the baseURL attribute:

```javascript
new URLPattern({ baseURL: 'https://example.com/' pathname: '/foo/:bar' });
```

The first is a bit awkward and the second causes the path to also be inherited.  If you override the pathname as in the example above this is fine, but consider a case where you care about search strings:

```javascript
new URLPattern({ baseURL: 'https://example.com/' search: '(.*)q=foo(.*)' });
```

Here you want to match any URL with the given query value, however the pathname was inherited as an exact `/` from the baseURL.  You need to add an additional `pathname: '/(.*)'` explicitly to match any pathname.

As an alternative we could add an `origin: https://example.com/` attribute.  It would function like baseURL, but would not apply the pathname leaving it as a wildcard.

**Comment by annevk** [comment]
I'd rather we make it explicit what needs to be ignored. Calling this `origin` feels a little weird as origins are typically not inputs (unless they are to be compared literally).

**Comment by wanderview** [comment]
Also, its not clear if people would expect baseURL type behavior from origin or more expect to be able to put a pattern in the origin.

I'll leave origin input attribute out for now.

**Comment by wanderview** [comment]
Closing this as we decided not to include an origin attribute.
