### ISSUE TITLE
passing base URL as a dictionary property vs a separate string argument

### ISSUE THREAD

**Issue by wanderview** [WICG/urlpattern#35]
So far I've been mostly aiming to have the base URL, if present, passed as a property on the dictionary argument.  For example:

```javascript
new URLPattern({ pathname: '/foo/bar', baseURL: 'https://example.com' });
```

And:

```javascript
p.test({ pathname: '/foo/bar', baseURL: 'https://example.com' });
```

I also have a TODO, though, to support a baseURL for the string URL input to test()/exec().  For example:

```javascript
p.test('/foo/bar', 'https://example.com');
```

@blakeembrey suggested maybe we should always support base URL as a second argument.  For example, the first two examples would look like this:

```javascript
new URLPattern({ pathname: '/foo/bar' }, 'https://example.com');

p.test({ pathname: '/foo/bar' }, 'https://example.com');
```

This also seems reasonable to me.  I think the one downside is that you lose the "named arguments" style of the dictionary.  We could possibly support both styles, though, and let developers choose which they prefer.

Thoughts?

**Comment by jeremyroman** [comment]
FWIW I don't have a strong preference but I think allowing it to existing in both places is potentially confusing. What does `new URLPattern({ pathname: '/foo/bar', baseURL: 'https://example.com/'}, 'https://example.net/')` do?

**Comment by wanderview** [comment]
I don't support that for constructor currently.  But I did just add support for it to test() and exec().  The webidl looks like:

```
boolean test(URLPatternInit input);
boolean test(USVString input, optional USVString baseURL);
```

Which means passing a second argument will coerce the first argument to a string.  So this will always return false:

```javascript
pattern.test({ pathname: '/foo/bar' }, 'https://example.com');
```

I could at least get this to an error message if I changed the webidl to:

```
typedef (USVString or URLPatternInit) URLPatternInput;
boolean test(URLPatternInput input, optional USVString baseURL);
```

But I chose not to do that since it seemed better to defer to webidl semantics.  I don't feel too strongly here if other think we should go a different way.

**Comment by wanderview** [comment]
Talked with @domenic this morning and he suggested we go with the union type to provide a more meaningful exception.  It provides a better experience for developers at the cost of a slightly harder to read spec.  We can add a note to the spec, though.

I think we should not support second baseURL argument for structured input for now.  We will throw an exception if the user tries.  If we get lots of requests for the feature, though, we can re-assess.

**Comment by wanderview** [comment]
This is now codified in the spec.
