### ISSUE TITLE
Consider alternatives to path to regex pattern

### ISSUE THREAD

**Issue by jasnell** [WICG/urlpattern#42]
Great work so far. Happy to see progress here. Just one quick thing I'd like to point out is that the regex approach here certainly is not the fastest. I haven't read through everything in detail get so forgive me if I've missed something. I wanted to at least point towards the radix based approach that the fastify framework uses for parsing and matching https://github.com/delvedor/find-my-way.

**Comment by wanderview** [comment]
I would say our goal so far, though, has been to focus on ergonomics over performance.  We've taken path-to-regexp's popularity as a signal of good ergonomics without significant performance issues.

Looking at the benchmarks from the link above it looks like the performance difference is in the microsecond range.  This seems unlikely to be significant in browser use cases.  I will admit, though, it could be more important in server environments.  Maybe this is an area where browser and server use cases diverge.

I'll take a closer look after I get back from holiday in January.  Thanks.

**Comment by wanderview** [comment]
There might be some overlap with our plans to restrict what kind of patterns can be used for some web platform apis like service workers.  Those restrictions are partially motivated by performance.

**Comment by jasnell** [comment]
The key for server side cases would just be flexibility in the implementation. That is, I'd prefer the api not to bake in any assumptions or requirements that regexp is used under the covers.

**Comment by blakeembrey** [comment]
This is a good call out, but worth noting the only part in `path-to-regexp` assuming regex patterns are optional patterns within the match, e.g. `/:foo(\d+)`. Those could be an optional feature, or omitted entirely for `URLPattern` support.

**Comment by wanderview** [comment]
Or optimizations are triggered if custom regexp groups are not used in the pattern.

**Comment by wanderview** [comment]
I'm going to close this one for now.  As discussed above, optimizations can be handled as an implementation detail.  Also, we chose path-to-regexp for ecosystem reasons due to its existing popular usage providing a well lit path to follow.
