### ISSUE TITLE
support unicode group names

### ISSUE THREAD

**Issue by wanderview** [WICG/urlpattern#46]
Currently path-to-regexp and URLPattern only support alphanumeric and underscore ASCII characters in a group name like `:foo`.  It would be good to allow other unicode characters to support developers working in different languages.

I can support this in URLPattern, but ideally it would be nice to align path-to-regexp to it as well.  I think to do this we would likely need two changes:

1. In addition to alphanumeric and underscore ASCII characters also allow unicode characters.
2. Support some kind of callback to encode unicode characters in other parts of the pattern.

@blakeembrey what do you think?  If you think this is reasonable I can work on a PR.

**Comment by blakeembrey** [comment]
Definitely makes sense, I can add support to `path-to-regexp` for the same things. The only thing that's limited me in the past is my knowledge of the set of characters to allow through - if we have the character groups I should be able to do it. For 2, is this more for encoding characters that aren't valid in the URL or just specific unicode? I have the same trouble here, but if we have those lists or you build it in another language, I can probably port it over.

**Comment by domenic** [comment]
> The only thing that's limited me in the past is my knowledge of the set of characters to allow through - if we have the character groups I should be able to do it

Probably ID_Start for the first character and ID_Nonstart after that? (the JS spec uses ID_Continue instead of ID_Nonstart, but https://unicode.org/reports/tr31/ seems to talk about ID_Nonstart...)

/cc @mathiasbynens

**Comment by wanderview** [comment]
Thanks.  I can try to make a PR to path-to-regexp upstream when I get to this.

**Comment by mathiasbynens** [comment]
> > The only thing that's limited me in the past is my knowledge of the set of characters to allow through - if we have the character groups I should be able to do it
> 
> ~Probably ID_Start for the first character and ID_Nonstart after that? (the JS spec uses ID_Continue instead of ID_Nonstart, but https://unicode.org/reports/tr31/ seems to talk about ID_Nonstart...)~

It depends on what you want to align with here. If the desire is to match JS, it goes [something like this](https://github.com/tc39/proposal-regexp-unicode-property-escapes#other-examples):

```js
const regexIdentifierStart = /[$_\p{ID_Start}]/u;
const regexIdentifierPart = /[$_\u200C\u200D\p{ID_Continue}]/u;
const regexIdentifierName = /^(?:[$_\p{ID_Start}])(?:[$_\u200C\u200D\p{ID_Continue}])*$/u;
```

> Probably XID_Start followed by XID_Continue, per https://unicode.org/reports/tr31/#Default_Identifier_Syntax

Hmm, I could see the argument for this as well, although I'd personally expect JS identifiers.

**Comment by wanderview** [comment]
I have my c++ prototype using the js identifiers as defined in v8 here:

https://source.chromium.org/chromium/chromium/src/+/master:v8/src/strings/char-predicates.cc;l=17-34;drc=be014256adea1552d4a044ef80616cdab6a7d549

The only thing I'm a bit leery of is supporting backslash within an identifier since it means something in other parts of the pattern.  It should work, though.

**Comment by wanderview** [comment]
Actually, I think the backslash could cause problems.  What if someone wants to put a backslashed literal right after the named group?  For example, something like `/:host\::port`.

I don't think we should allow backslash in group names.

**Comment by domenic** [comment]
Yeah I think backslashes aren't necessary. I believe that's for supporting things like `let _\u0487 = 5`, i.e. letting people type only ASCII while still getting an identifier name of `_҇`.

The corresponding scenario for URLPattern, where you want to type only ASCII while still getting an international identifier name, would be something like `new URLPattern("/foo/:_\u0487")`. But in that case the JS engine would already treat that string as `"/foo/:_҇"` by the time the spec and implementation saw them.

So, the backslash-escape handling should already be taken care of by the JS engine's string parser, and the URLPattern spec and implementation shouldn't need to worry about them.

**Comment by wanderview** [comment]
Do you javascript identifiers do anything special for RTL languages?  I'm just wondering since ID_START vs ID_CONTINUE suggest different treatment for the first character which might be reversed for RTL?

**Comment by mathiasbynens** [comment]
> Do javascript identifiers do anything special for RTL languages?

No. The patterns in https://github.com/WICG/urlpattern/issues/46#issuecomment-775461951 accurately describe which code points get matched, in which positions.

**Comment by wanderview** [comment]
This is now codified in the spec.
