### ISSUE TITLE
Add link to the spec to the GitHub project page

### ISSUE THREAD

**Issue by domenic** [WICG/urlpattern#80]
Sad:

![image](https://user-images.githubusercontent.com/617481/129243447-8c1ef357-6b83-4e75-8161-e980c062cdca.png)

Nice:

![image](https://user-images.githubusercontent.com/617481/129243482-637b3cfd-7bd8-4ade-9b5c-6bdf62f3810d.png)

(You could also turn off releases/packages/environments in the sidebar via settings if you wanted.)

**Comment by wanderview** [comment]
Fixed.  Thanks.
