### ISSUE TITLE
Arguments in `compiling a component` call are completely wrong

### ISSUE THREAD

**Issue by crowlKats** [WICG/urlpattern#82]
https://wicg.github.io/urlpattern/#ref-for-constructor-string-parser②⑥

> Let protocol component be the result of compiling a component given protocol string, canonicalize a protocol, and default options\.

only the first argument fits the declaration of https://wicg.github.io/urlpattern/#urlpattern-internals

>  To compile a component given a string input, options options, and encoding callback encoding callback:​

**Comment by wanderview** [comment]
Ouch.  Sorry for all these mistakes.  Unfortunately catching this stuff often falls to the second implementer since there is not a good way to run the spec through a test.
