### ISSUE TITLE
Missing equality in conditions

### ISSUE THREAD

**Issue by crowlKats** [WICG/urlpattern#89]
https://wicg.github.io/urlpattern/#ref-for-constructor-string-parser②⑥

> If the result of running protocol component matches a special scheme given protocol component

https://wicg.github.io/urlpattern/#parse-a-constructor-string

> If the result of running next is authority slashes given parser:​

... is what? Missing explicit equality (at least i assume from what i saw in other parts of the spec)

**Comment by wanderview** [comment]
Yea, these should have "is true, then".  Thanks for catching this and all the other problems.  I'll fix on Monday.
