### ISSUE TITLE
Wrong character for part modifier

### ISSUE THREAD

**Issue by crowlKats** [WICG/urlpattern#91]
https://wicg.github.io/urlpattern/#ref-for-options⑧

> If part’s modifier is "zero\-or\-more" then append "?" to the end of result\.

Shouldn't this be "append `"*"`"?

**Comment by wanderview** [comment]
Yes!  Good catch (here and everywhere else).

**Comment by wanderview** [comment]
Actually, the spec is correct in this case.  The note above tries to describe this with "If zero values are permitted then a final optional modifier may be appended".  The repeating nature of the zero-or-more modifier has already been captured in the preceding regexp text.

Does that make sense?

**Comment by wanderview** [comment]
Going to close for now, but please re-open if you think this is wrong.  Thanks again.

**Comment by crowlKats** [comment]
> Actually, the spec is correct in this case. The note above tries to describe this with "If zero values are permitted then a final optional modifier may be appended". The repeating nature of the zero-or-more modifier has already been captured in the preceding regexp text.
> 
> Does that make sense?

Oh I see, yes, my bad.
