### ISSUE TITLE
Simplify assign and increment

### ISSUE THREAD

**Issue by crowlKats** [WICG/urlpattern#93]
https://wicg.github.io/urlpattern/#ref-for-constructor-string-parser-state⑥

> Set parser’s component start to parser’s token index \+ skip\.
> 
> Increment parser’s token index by skip\.

This could be simplified by incrementing `token index` before setting `component start`, as in 

> Increment parser’s token index by skip\.
>
> Set parser’s component start to parser’s token index.

**Comment by wanderview** [comment]
Good idea.  The current structure is left over from previous versions of the implementation that applied "skip" differently to the two values.
