### ISSUE TITLE
Part's name is never null?

### ISSUE THREAD

**Issue by crowlKats** [WICG/urlpattern#95]
https://wicg.github.io/urlpattern/#ref-for-options⑧

> Assert:​ part’s name is not the empty string and is not null\.

When can part's name ever be null? I could not find any instance of this being possible

**Comment by wanderview** [comment]
Yea, this is just asserting that invariant.  I guess that's kind of already captured because we say the "name" is a string and we don't say its a "string or null" when we declare it at:

https://wicg.github.io/urlpattern/#part-name

I'll drop the null bit from the assertion.
